# Generated by Django 6.0.2 on 2026-02-26 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Login Successful'), ('LOGIN_FAILED', 'Login Failed'), ('LOGOUT', 'Logout'), ('PASSWORD_CHANGED', 'Password Changed'), ('PASSWORD_RESET', 'Password Reset'), ('2FA_ENABLED', '2FA Enabled'), ('2FA_DISABLED', '2FA Disabled'), ('2FA_RECOVERY', '2FA Recovery Used'), ('DEVICE_TRUSTED', 'Device Trusted'), ('DEVICE_REVOKED', 'Device Revoked'), ('ACCOUNT_LOCKED', 'Account Locked'), ('ACCOUNT_UNLOCKED', 'Account Unlocked'), ('PROFILE_UPDATED', 'Profile Updated'), ('USER_REGISTERED', 'User Registered'), ('USER_VERIFIED', 'User Verified')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('was_successful', models.BooleanField(default=True)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('device_id', models.CharField(blank=True, max_length=255)),
                ('device_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-login_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='userotp',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='userdevice',
            name='accounts_us_user_id_ecbe10_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(default=list, help_text='Hashed backup codes for 2FA recovery'),
        ),
        migrations.AddField(
            model_name='user',
            name='security_profile',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='TOTP secret key for authenticator apps', max_length=255),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='total_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='trusted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userotp',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('western_urban', 'Western Area Urban'), ('western_rural', 'Western Area Rural'), ('northern', 'Northern Province'), ('southern', 'Southern Province'), ('eastern', 'Eastern Province'), ('north_west', 'North West Province')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('SMS', 'SMS Verification'), ('TOTP', 'Authenticator App')], default='SMS', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual Saver'), ('GROUP_ADMIN', 'Group Administrator'), ('ADMIN', 'System Administrator')], db_index=True, default='INDIVIDUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_type',
            field=models.CharField(choices=[('MOBILE', 'Mobile App'), ('WEB', 'Web Browser'), ('USSD', 'USSD')], default='WEB', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='purpose',
            field=models.CharField(choices=[('LOGIN', 'Login Verification'), ('REGISTER', 'Registration Verification'), ('RESET_PASSWORD', 'Password Reset'), ('TWO_FACTOR', 'Two-Factor Auth'), ('TWO_FACTOR_SETUP', '2FA Setup'), ('TWO_FACTOR_DISABLE', '2FA Disable')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-date_joined'], name='accounts_us_date_jo_bab293_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', '-last_used'], name='accounts_us_user_id_d7ceb4_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_id'], name='accounts_us_device__9d02e7_idx'),
        ),
        migrations.AddIndex(
            model_name='userotp',
            index=models.Index(fields=['expires_at'], name='accounts_us_expires_c6811e_idx'),
        ),
        migrations.AddField(
            model_name='securityevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userloginhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['user', '-created_at'], name='accounts_se_user_id_c88cbb_idx'),
        ),
        migrations.AddIndex(
            model_name='securityevent',
            index=models.Index(fields=['event_type', 'created_at'], name='accounts_se_event_t_67c552_idx'),
        ),
        migrations.AddIndex(
            model_name='userloginhistory',
            index=models.Index(fields=['user', '-login_time'], name='accounts_us_user_id_98058e_idx'),
        ),
    ]
